# Generated by Django 5.2.13 on 2026-05-03 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='DocumentTag',
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.documenttag'),
        ),
        migrations.AlterField(
            model_name='textregion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='regions', to='documents.documenttag'),
        ),
        migrations.CreateModel(
            name='RegionAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='documents.documenttag')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='documents.textregion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
