# Generated by Django 5.2.13 on 2026-05-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documenttag_alter_document_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='cloudinary_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='cloudinary_image_public_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='cloudinary_image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
